language: node_js
node_js:
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services:
  - mongodb
  - redis-server
notifications:
  slack: podyumdev:yeYnhHvGJJ91UIovhEi1fEKr
